// flow-typed signature: cbbd4b8dda98c9c80b07e25ddb97d09b
// flow-typed version: <<STUB>>/haste-map-webpack-resolver_v^1.0.7/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'haste-map-webpack-resolver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'haste-map-webpack-resolver' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'haste-map-webpack-resolver/index' {
  declare module.exports: $Exports<'haste-map-webpack-resolver'>;
}
declare module 'haste-map-webpack-resolver/index.js' {
  declare module.exports: $Exports<'haste-map-webpack-resolver'>;
}
