// flow-typed signature: 781c3fb66c57dc24e534d417ce88998d
// flow-typed version: <<STUB>>/jest-haste-map_v^18.1.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-haste-map'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-haste-map' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-haste-map/build/constants' {
  declare module.exports: any;
}

declare module 'jest-haste-map/build/crawlers/node' {
  declare module.exports: any;
}

declare module 'jest-haste-map/build/crawlers/watchman' {
  declare module.exports: any;
}

declare module 'jest-haste-map/build/HasteFS' {
  declare module.exports: any;
}

declare module 'jest-haste-map/build/index' {
  declare module.exports: any;
}

declare module 'jest-haste-map/build/lib/docblock' {
  declare module.exports: any;
}

declare module 'jest-haste-map/build/lib/extractRequires' {
  declare module.exports: any;
}

declare module 'jest-haste-map/build/lib/getPlatformExtension' {
  declare module.exports: any;
}

declare module 'jest-haste-map/build/ModuleMap' {
  declare module.exports: any;
}

declare module 'jest-haste-map/build/types' {
  declare module.exports: any;
}

declare module 'jest-haste-map/build/worker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-haste-map/build/constants.js' {
  declare module.exports: $Exports<'jest-haste-map/build/constants'>;
}
declare module 'jest-haste-map/build/crawlers/node.js' {
  declare module.exports: $Exports<'jest-haste-map/build/crawlers/node'>;
}
declare module 'jest-haste-map/build/crawlers/watchman.js' {
  declare module.exports: $Exports<'jest-haste-map/build/crawlers/watchman'>;
}
declare module 'jest-haste-map/build/HasteFS.js' {
  declare module.exports: $Exports<'jest-haste-map/build/HasteFS'>;
}
declare module 'jest-haste-map/build/index.js' {
  declare module.exports: $Exports<'jest-haste-map/build/index'>;
}
declare module 'jest-haste-map/build/lib/docblock.js' {
  declare module.exports: $Exports<'jest-haste-map/build/lib/docblock'>;
}
declare module 'jest-haste-map/build/lib/extractRequires.js' {
  declare module.exports: $Exports<'jest-haste-map/build/lib/extractRequires'>;
}
declare module 'jest-haste-map/build/lib/getPlatformExtension.js' {
  declare module.exports: $Exports<'jest-haste-map/build/lib/getPlatformExtension'>;
}
declare module 'jest-haste-map/build/ModuleMap.js' {
  declare module.exports: $Exports<'jest-haste-map/build/ModuleMap'>;
}
declare module 'jest-haste-map/build/types.js' {
  declare module.exports: $Exports<'jest-haste-map/build/types'>;
}
declare module 'jest-haste-map/build/worker.js' {
  declare module.exports: $Exports<'jest-haste-map/build/worker'>;
}
