// flow-typed signature: 9eceaf633b01b6236699a073eb8d5d36
// flow-typed version: <<STUB>>/koa-connect-history-api-fallback_v^0.3.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-connect-history-api-fallback'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-connect-history-api-fallback' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-connect-history-api-fallback/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-connect-history-api-fallback/src/index.js' {
  declare module.exports: $Exports<'koa-connect-history-api-fallback/src/index'>;
}
