// flow-typed signature: ee3fffd89a7d0443afae1541b231ebe2
// flow-typed version: <<STUB>>/koa-proxy_v^0.7.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-proxy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-proxy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-proxy/index' {
  declare module.exports: $Exports<'koa-proxy'>;
}
declare module 'koa-proxy/index.js' {
  declare module.exports: $Exports<'koa-proxy'>;
}
