// flow-typed signature: e348a9ab48e4fb6fc39eb4ec09b47f4d
// flow-typed version: <<STUB>>/promise-monofill_v^1.0.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'promise-monofill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'promise-monofill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'promise-monofill/example' {
  declare module.exports: any;
}

declare module 'promise-monofill/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'promise-monofill/example.js' {
  declare module.exports: $Exports<'promise-monofill/example'>;
}
declare module 'promise-monofill/index' {
  declare module.exports: $Exports<'promise-monofill'>;
}
declare module 'promise-monofill/index.js' {
  declare module.exports: $Exports<'promise-monofill'>;
}
declare module 'promise-monofill/test.js' {
  declare module.exports: $Exports<'promise-monofill/test'>;
}
